version: "3.4"

services:
  mysql-container:
    container_name: mysql-container
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=1
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    restart: always
    volumes:
      - mysql-container:/var/lib/mysql:rw
    image: 'mysql:latest'
  docker_spring:
    depends_on:
      - mysql-container
    container_name: docker_spring
    ports:
      - '8089:8089'
    image: abirhalouani/achat

volumes:
  mysql-container: { }
